#!/bin/bash

# https://www.youtube.com/watch?v=8ga0xhZuG6k&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=17&ab_channel=LearnLinuxTV
echo "https://www.youtube.com/watch?v=8ga0xhZuG6k&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=17&ab_channel=LearnLinuxTV"
