#!/bin/bash

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
source $SCRIPT_PATH/_paremeters

get-secret-value() {
    echo "$(aws secretsmanager get-secret-value \
        --secret-id $1 | jq -r .SecretString)"
}

CURRENT_STR="$(get-secret-value "$NAME")"

echo $CURRENT_STR

create_new_secret_string() {
    NOW="$(date +"%Y-%m-%d %H-%M-%S")"
    echo "$(jq '.value = "'"$NOW"'"' <<< "$CURRENT_STR")"
}

NEW_STR="$(create_new_secret_string)"
# Remove new line from the string
NEW_STR="$(echo $NEW_STR | tr -d "\n")"

aws secretsmanager update-secret \
    --secret-id $NAME \
    --secret-string "$NEW_STR"

echo
echo "Updated value"
echo "$(get-secret-value "$NAME")"