#!/bin/bash

# https://www.cyberciti.biz/faq/bash-for-loop/
# https://www.geeksforgeeks.org/bash-scripting-for-loop/

echo "1. Simple For loop"
for n in "Item 1" "Item 2" "Item 3"; do
    echo $n
done

echo -e "\n2. Range-based for loop, inclusive at the 1 and 3"
for n in {1..3}; do
    echo $n
done

echo -e "\n3. Range-based for loop by step"
for n in {1..5..2}; do
    echo $n
done

echo -e "\n4. Array iteration for loops"
s=(
    "basketball"
    "baseball"
)
for n in ${s[@]}; do
    echo $n
done

echo -e "\n5. C-Styled for loops - using C syntax"
n=3
for ((i=1 ; i<=$n ; i++)); 
do
    echo $i
done

