#!/bin/bash

WORKING_DIR="."
files=($(cd $WORKING_DIR && find . -mindepth 1 -maxdepth 1 -type f -printf '%f\n'))

# If need to sort
files=($(echo "${files[@]}" | tr ' ' '\n' | sort))

# It is possible to put the directory names into an array and then loop through it
for file in "${files[@]}"; do
  echo "$file"
done
