#!/bin/bash

red() {
    echo '\033[1;31m'"$1"'\033[0m'
}

echo -e "The following extensions have been tested\n"
echo -e "1. The $(red "Bash IDE") helps on bash syntax"
echo -e "2. The $(red "shell-format") extension helps to format the bash scripts"
