#!/bin/bash

# https://www.youtube.com/watch?v=cul9r5uSNTE&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=14&ab_channel=LearnLinuxTV
echo "https://www.youtube.com/watch?v=cul9r5uSNTE&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=14&ab_channel=LearnLinuxTV"