#!/bin/bash

# Only keep the top-level directories that have changed in the last commit
# 1. he grep / ensures we only get directories,
# 2. cut -d/ -f1 gets the top-level directory,
# 3. sort -u removes duplicates

D=($(git diff --name-only HEAD^1 HEAD | grep / | cut -d/ -f1 | sort -u))

echo "${D[@]}"
