#!/bin/bash

# Need to make the variables available
PROJECT_BASE="/home/song/Sandbox"
PROJECT_NAME="bash-examples-miscellaneous"

ALLOWED_BRANCH="master"
COMMIT_MESSAGE="Updated the bash-examples-miscellaneous"

ACTIVE_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$ACTIVE_BRANCH" != "$ALLOWED_BRANCH" ]; then
    echo "Disabled for all branches except $ACTIVE_BRANCH"
    exit 1
fi

git reset --soft HEAD~
git add -A && git commit -m "$COMMIT_MESSAGE"
git push -f

echo && git fetch
echo -e "Wait for a second ...\n" && sleep 1

echo "Changes in the last commit:"
git diff HEAD~1 HEAD --name-only && echo

git log -2