#!/bin/bash -e

# Need to make the variables available
PROJECT_BASE="/home/song/Sandbox"
PROJECT_NAME="bash-examples-miscellaneous"

echo "$PROJECT_NAME:"
cd $PROJECT_BASE/$PROJECT_NAME

git fetch

echo && echo "Changes in the last commit:"
git diff HEAD~1 HEAD --name-only && echo

if [[ $# -eq 0 ]]; then
	git log -2
else
	git log "$@"
fi
