#!/bin/bash

declare -A lookup_dict

lookup_dict["key_1"]="value 1"
lookup_dict["key 2"]="value 2"

key="key_1"
echo "${lookup_dict[$key]}"

key="key 2"
echo "${lookup_dict[$key]}"

if [ "${lookup_dict["Non-exist key"]}" = "" ]; then
    echo "When key non-exist, the value is an empty string"
fi
