#!/bin/bash

# https://www.youtube.com/watch?v=8ga0xhZuG6k&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=17&ab_channel=LearnLinuxTV
echo "https://www.youtube.com/watch?v=8ga0xhZuG6k&list=PLT98CRl2KxKGj-VKtApD8-zCqSaN2mD4w&index=17&ab_channel=LearnLinuxTV"

echo "This script is not set to run"
echo "But you can take a look at the code example"
exit 0

# rsync -h
# 1. The "/" in the source-dir/ indicates to backup all the files in the source-dir into a directory named dest-dir
# 2. If an item in a excluded directory is included, the --include need to be specified before the exclude
# 3. Multiple includes/excludeds are allowed
# 4. The "-a" archive mode - https://www.baeldung.com/linux/rsync-archive-mode
#   - if the -a option is passed. It synchronizes the directories recursively.
#   - It also keeps the ownership of users and groups, permissions, symbolic links (symlinks), and timestamps.
#   - In fact, it’s a collection of the -rlptgoD options.

rsync -a --stats source-dir/ dest-dir \
    --include excluded-dir1/sub-dir \
    --exclude excluded-dir1/* \
    --exclude excluded-dir2 \
    --delete-excluded


# It is possible to dry-run
# --dry-run, -n => perform a trial run with no changes made
