#!/bin/bash

# Array entry separator is space
arrary=("item 1" "item 2")

check() {
    v="$1"

    # The spaces are important fot the correct comparison
    if [[ " ${arrary[@]} " =~ " $v " ]]
    then
        echo "$v is in the list"
    else
        echo "$v is not in the list"
    fi
}

check "item 1"
check "item 2"
check "item 3"