#!/bin/bash

# array entries as selection options
items=(
    "Item no.0"
    "Item no.1"
    "Item no.2"
)

for i in "${!items[@]}"; do
    echo "$i - ${items[$i]}"
done
echo -n "Please select "
read -r i

if [[ ! $i =~ ^[0-9]+$ ]]; then
    echo "You need type an integer >= 0"
    exit
fi

item="${items[$i]}"
if [[ -z ${item} ]]; then
    echo "Your selection $i is not valid"
    exit
fi

echo "You chose $item"
