#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Type in some arguments to run the example"
    exit
fi

echo '$#'" is the number of the arguments - $#"
echo '$@'" is all the arguments - $@"
echo '$0'" is the script path - $0"
echo '$1'" is the first argument- $1"

echo
echo "Looping all the argumets"
# In a special case
# .scripts/01-basics/16-arguments/example a b "c c" may be recognized as 4 arguments
for arg in $@; do
    echo $arg
done
